<?php 

/*****
 * Author: Ethan Gruber
 * Date: October 2022
 * Function: Transform the Shubin collection spreadsheet into TEI documents with IIIF image references
 */

$collections = generate_json('https://docs.google.com/spreadsheets/d/e/2PACX-1vRGoDJlDraepfvM_NSxbNkOatn6JR6KakrivUDrB0bksuM2fWmXHR94qB19P_Ch90kGVGwLdemFtgKo/pub?gid=0&single=true&output=csv');

foreach ($collections as $collection){
	$id = $collection['ID']
	
	//start TEI file
	$doc->startElement('TEI');
		$doc->writeAttribute('xmlns', 'http://www.tei-c.org/ns/1.0');
		$doc->writeAttribute('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance');
		$doc->writeAttribute('xsi:schemaLocation', 'http://www.tei-c.org/ns/1.0 http://www.tei-c.org/release/xml/tei/custom/schema/xsd/tei_all.xsd');
		$doc->writeAttribute('xml:id', $id);
		
		//TEI Header
		$doc->startElement('teiHeader');
			$doc->startElement('fileDesc');
				$doc->startElement('titleStmt');
					$doc->writeElement('title', $collection['Title']);
					$doc->startElement('author');
						$doc->startElement('persName');
							$doc->writeAttribute('ref', 'http://numismatics.org/authority/shubin_michael');
							$doc->text('Shubin, Michael');
						$doc->endElement();
					$doc->endElement();
				$doc->endElement();
				
				//these items probably shouldn't have a publisher
				$doc->startElement('publicationStmt');
					$doc->startElement('publisher');
						$doc->writeElement('name', 'American Numismatic Society');
						$doc->startElement('idno');
							$doc->writeAttribute('type', 'URI');
							$doc->text('http://numismatics.org/authority/american_numismatic_society');
						$doc->endElement();
					$doc->endElement();
					$doc->writeElement('pubPlace', 'New York (N.Y.)');
				$doc->endElement();
				
				//sourceDesc
				$doc->startElement('sourceDesc');
					$doc->startElement('biblStruct');
						$doc->startElement('monogr');
							$doc->writeElement('title', $collection['Title']);
							$doc->startElement('author');
								$doc->startElement('persName');
									$doc->writeAttribute('ref', 'http://numismatics.org/authority/shubin_michael');
									$doc->text('Shubin, Michael');
								$doc->endElement();
							$doc->endElement();
							$doc->startElement('imprint');
								$doc->writeElement('date', 'unknown');
							$doc->endElement();
						$doc->endElement();
					$doc->endElement();
				//add extent later
				$doc->endElement();
			
			//end fileDesc
			$doc->endElement();
			
			//profileDesc (general document metadata)
			$doc->startElement('profileDesc');
				$doc->startElement('langUsage');
					$doc->startElement('language');
						$doc->writeAttribute('ident', 'en');
						$doc->text('English');
					$doc->endElement();
				$doc->endElement();
			
				$doc->startElement('textClass');
					$doc->startElement('classCode');
						$doc->writeAttribute('scheme', 'http://vocab.getty.edu/aat/');
						$doc->text('300264354');
					$doc->endElement();
				$doc->endElement();
			//end profileDesc
			$doc->endElement();
			
			$doc->startElement('revisionDesc');
			$doc->startElement('change');
			$doc->writeAttribute('when', substr(date(DATE_W3C), 0, 10));
			$doc->text('Generated TEI document by processing list of files generated by ImageMagick identify library, after sequential image renaming.');
			$doc->endElement();
			$doc->endElement();
	
	
		//end TEI header
		$doc->endElement();
	
	//end TEI file
	$doc->endElement();
	
	//close file
	$doc->endDocument();
	$doc->flush();
}

//write CSV into an array
function generate_json($doc){
	$keys = array();
	$array = array();
	
	$csv = csvToArray($doc, ',');
	
	// Set number of elements (minus 1 because we shift off the first row)
	$count = count($csv) - 1;
	
	//Use first row for names
	$labels = array_shift($csv);
	
	foreach ($labels as $label) {
		$keys[] = $label;
	}
	
	// Bring it all together
	for ($j = 0; $j < $count; $j++) {
		$d = array_combine($keys, $csv[$j]);
		$array[$j] = $d;
	}
	return $array;
}

// Function to convert CSV into associative array
function csvToArray($file, $delimiter) {
	if (($handle = fopen($file, 'r')) !== FALSE) {
		$i = 0;
		while (($lineArray = fgetcsv($handle, 4000, $delimiter, '"')) !== FALSE) {
			for ($j = 0; $j < count($lineArray); $j++) {
				$arr[$i][$j] = $lineArray[$j];
			}
			$i++;
		}
		fclose($handle);
	}
	return $arr;
}

?>